'use client'

import Image from 'next/image'
import { useState, type ChangeEvent } from 'react'
import { skipImageOptimization } from '@/lib/auth'
import { useCart } from '@/context/CartContext'
import { useAuth } from '@/context/AuthContext'
import { useToast } from '@/context/ToastContext'
import { useZones } from '@/context/ZonesContext'
import { linePricing, formatInr } from '@/lib/cartSpecs'
import { authFetch, trackActivity } from '@/lib/supabaseClient'
import { downloadBoq, EMPTY_BOQ_DETAILS, type BoqProjectDetails as BoqDetails } from '@/lib/boq'

const PAN_PATTERN = /^[A-Z]{5}[0-9]{4}[A-Z]$/

export default function CartDrawer() {
  const { items, isOpen, closeCart, removeItem, updateQty, updateDiscount, clearCart } = useCart()
  const { user, can } = useAuth()
  const { toast } = useToast()
  const { getZoneById } = useZones()
  const [sending, setSending] = useState(false)
  const [sent, setSent]       = useState(false)
  const [note, setNote]       = useState('')
  const [downloadingPdf, setDownloadingPdf] = useState(false)
  // BOQ details form — values are kept while the page is open, so a second
  // download for the same project doesn't need retyping.
  const [boqFormOpen, setBoqFormOpen] = useState(false)
  const [boqDetails, setBoqDetails]   = useState<BoqDetails>(EMPTY_BOQ_DETAILS)
  const setBoqField = (k: keyof BoqDetails) => (e: ChangeEvent<HTMLInputElement>) =>
    setBoqDetails(d => ({ ...d, [k]: e.target.value }))
  const panValue   = boqDetails.architectPan.trim().toUpperCase()
  const panInvalid = panValue !== '' && !PAN_PATTERN.test(panValue)

  const totalQty = items.reduce((s, i) => s + i.quantity, 0)

  // Quote totals from each line's D.P. × qty less its discount (excl. GST).
  const quoteTotals = items.reduce((t, item) => {
    const p = linePricing(item)
    if (p.unit === null || p.total === null) return { ...t, unpriced: t.unpriced + 1 }
    const gross = p.unit * item.quantity
    return { ...t, hasPrices: true, gross: t.gross + gross, net: t.net + p.total, discount: t.discount + (gross - p.total) }
  }, { hasPrices: false, gross: 0, net: 0, discount: 0, unpriced: 0 })

  // Build readable context line per item
  const itemContext = (item: ReturnType<typeof useCart>['items'][0]) => {
    if (item.browseMode === 'product') {
      const parts = [item.productCategory, item.productSubcategory, item.productTypeName].filter(Boolean)
      return parts.join(' › ')
    }
    return getZoneById(item.zone)?.label ?? item.zone ?? '—'
  }

  // Compact item list for the activity log.
  const quoteSummary = () => items.map(i => ({ productCode: i.productCode, quantity: i.quantity, selection: i.selection }))

  const buildEmailBody = () => {
    const header =
      `LEDLUM — Quote Request\n${'='.repeat(50)}\n\n` +
      `Partner : ${user?.name ?? 'Unknown'}\n` +
      `Company: ${user?.company ?? '—'}\n` +
      `Email  : ${user?.email ?? '—'}\n` +
      `Date   : ${new Date().toLocaleString('en-IN')}\n\n` +
      `${'─'.repeat(50)}\nITEMS\n${'─'.repeat(50)}\n`

    const rows = items.map((item, i) => {
      const context = item.browseMode === 'product'
        ? `Category: ${itemContext(item)}`
        : `Zone    : ${getZoneById(item.zone)?.label ?? item.zone}`
      const specs = Object.entries(item.selection)
        .filter(([, v]) => v)
        .map(([k, v]) => `  • ${k.charAt(0).toUpperCase() + k.slice(1)}: ${v}`)
        .join('\n')
      const p = linePricing(item)
      const price = p.unit === null
        ? '   Price   : on request'
        : `   D.P.    : ${formatInr(p.unit)}${p.disc ? `  · Disc ${p.disc}% → ${formatInr(p.net!)}` : ''}\n   Total   : ${formatInr(p.total!)}`
      return `\n${i + 1}. ${item.productName}\n   ${context}\n   Quantity: ${item.quantity}\n${price}\n${specs || '   (No configuration selected)'}`
    }).join('\n')

    const totalsText = quoteTotals.hasPrices
      ? `Subtotal (D.P.): ${formatInr(quoteTotals.gross)}\n` +
        (quoteTotals.discount > 0 ? `Discount      : − ${formatInr(quoteTotals.discount)}\n` : '') +
        `Total         : ${formatInr(quoteTotals.net)} (excl. GST)\n\n`
      : ''

    const footer =
      `\n\n${'─'.repeat(50)}\n` +
      `Total items: ${totalQty}\n` +
      totalsText +
      `\nPlease review and confirm pricing before processing.\n\n` +
      `Generated by LEDLUM Catalog System`

    return header + rows + footer
  }

  const handleDownloadPDF = async () => {
    if (items.length === 0 || downloadingPdf || panInvalid) return
    setBoqFormOpen(false)
    setDownloadingPdf(true)
    try {
      // Project details from the BOQ form; empty fields print as blank space.
      await downloadBoq({
        lines: items,
        details: boqDetails,
        preparedBy: user?.name ?? '',
        dealerName: user?.company ?? user?.name ?? '',
      })
      trackActivity('boq_downloaded', { items: quoteSummary(), totalQty })
    } catch (err) {
      console.error('[CartDrawer] PDF export failed:', err)
      toast('Failed to generate PDF', 'error')
    } finally {
      setDownloadingPdf(false)
    }
  }

  // Emails the quote to LEDLUM (projects@ledlumlighting.com) via /api/quote-request;
  // the partner gets a confirmation copy. Logged server-side as 'quote_sent'.
  const handleSendQuote = async () => {
    if (items.length === 0 || sending) return
    setSending(true)
    try {
      const res = await authFetch('/api/quote-request', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          note,
          project: boqDetails,   // same project details as the BOQ form — saved with the quote
          items: items.map(i => ({
            productCode:  i.productCode,
            productName:  i.productName,
            productImage: i.productImage,
            productSpecs: i.productSpecs,   // snapshot, so the BOQ can be re-downloaded from My Quotes
            context:      itemContext(i),
            quantity:     i.quantity,
            selection:    i.selection,
            discount:     i.discount ?? 0,   // price itself is re-read on the server
          })),
        }),
      })
      const data = await res.json().catch(() => ({}))
      if (!res.ok) { toast(data.error ?? 'Could not send your quote request', 'error'); return }
      setSent(true); setNote('')
      toast(
        `Quote ${data.quoteNo ? `${data.quoteNo} ` : ''}sent to LEDLUM${data.confirmationSent ? ' — a copy has been emailed to you' : ''}. See it in My Account.`,
        'success',
      )
      setTimeout(() => setSent(false), 4000)
    } catch {
      toast('Network error — quote request not sent', 'error')
    } finally {
      setSending(false)
    }
  }

  const handleCopyQuote = () => {
    navigator.clipboard.writeText(buildEmailBody())
    trackActivity('quote_copied', { items: quoteSummary(), totalQty })
    toast('Quote copied to clipboard', 'success')
  }

  return (
    <>
      <div
        className={`fixed inset-0 z-40 bg-black/40 transition-opacity duration-300 ${isOpen ? 'opacity-100 pointer-events-auto' : 'opacity-0 pointer-events-none'}`}
        onClick={closeCart}
      />

      <div className={`fixed inset-y-0 right-0 z-50 w-full max-w-md bg-white shadow-2xl flex flex-col transition-transform duration-300 ease-[cubic-bezier(0.25,0.46,0.45,0.94)] ${isOpen ? 'translate-x-0' : 'translate-x-full'}`}>
        <div className="h-1 bg-gradient-to-r from-primary to-primary-dark flex-shrink-0" />

        {/* Header */}
        <div className="flex items-center justify-between px-6 py-4 border-b border-gray flex-shrink-0">
          <div>
            <h2 className="text-lg font-bold font-bai text-foreground flex items-center gap-2">
              <svg width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2">
                <circle cx="9" cy="21" r="1"/><circle cx="20" cy="21" r="1"/>
                <path d="M1 1h4l2.68 13.39a2 2 0 0 0 2 1.61h9.72a2 2 0 0 0 2-1.61L23 6H6"/>
              </svg>
              Quote Cart
            </h2>
            <p className="text-xs text-gray-text font-pop mt-0.5">
              {user?.company ?? user?.name} · {totalQty} item{totalQty !== 1 ? 's' : ''}
            </p>
          </div>
          <button
            onClick={closeCart}
            className="w-8 h-8 rounded-full border border-gray flex items-center justify-center text-gray-dark hover:bg-primary hover:text-white hover:border-primary transition-all text-sm"
          >✕</button>
        </div>

        {/* Items */}
        <div className="flex-1 overflow-y-auto">
          {items.length === 0 ? (
            <div className="flex flex-col items-center justify-center h-full text-center px-8">
              <svg className="opacity-10 mb-4" width="56" height="56" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1">
                <circle cx="9" cy="21" r="1"/><circle cx="20" cy="21" r="1"/>
                <path d="M1 1h4l2.68 13.39a2 2 0 0 0 2 1.61h9.72a2 2 0 0 0 2-1.61L23 6H6"/>
              </svg>
              <p className="text-gray-dark font-bai text-sm">Your quote cart is empty</p>
              <p className="text-gray-dark text-xs font-pop mt-1">Browse products and add configurations</p>
            </div>
          ) : (
            <div className="divide-y divide-gray">
              {items.map(item => (
                <div key={item.id} className="px-6 py-4">
                  <div className="flex gap-3">
                    {/* Thumb */}
                    <div className="relative w-14 h-14 bg-white border border-gray rounded-lg overflow-hidden flex-shrink-0 flex items-center justify-center">
                      {item.productImage ? (
                        <Image src={item.productImage} alt={item.productCode} fill sizes="56px" className="object-contain" unoptimized={skipImageOptimization(item.productImage)} />
                      ) : (
                        <svg className="opacity-20" width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.5">
                          <rect x="3" y="3" width="18" height="18" rx="2"/><circle cx="8.5" cy="8.5" r="1.5"/><polyline points="21 15 16 10 5 21"/>
                        </svg>
                      )}
                    </div>

                    <div className="flex-1 min-w-0">
                      <div className="flex items-start justify-between gap-2">
                        <span className="font-bold text-sm font-bai text-foreground truncate">{item.productName}</span>
                        <button onClick={() => removeItem(item.id)} className="text-gray-dark hover:text-primary transition-colors flex-shrink-0 mt-0.5">
                          <svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2">
                            <polyline points="3 6 5 6 21 6"/>
                            <path d="M19 6v14a2 2 0 0 1-2 2H7a2 2 0 0 1-2-2V6m3 0V4a1 1 0 0 1 1-1h4a1 1 0 0 1 1 1v2"/>
                          </svg>
                        </button>
                      </div>

                      {/* Price (D.P. per unit) */}
                      <p className="mt-0.5 text-xs font-pop text-gray-text">
                        {item.unitPrice != null
                          ? <>D.P. <span className="font-semibold text-foreground">{formatInr(item.unitPrice)}</span> / unit</>
                          : <span className="text-gray-dark">Price on request</span>}
                      </p>

                      {/* Selection chips */}
                      {Object.entries(item.selection).filter(([, v]) => v).length > 0 && (
                        <div className="flex flex-wrap gap-1 mt-1.5">
                          {Object.entries(item.selection).filter(([, v]) => v).map(([k, v]) => (
                            <span key={k} className="text-[9px] bg-gray border border-gray-mid rounded-full px-2 py-0.5 font-pop text-gray-text">
                              {v}
                            </span>
                          ))}
                        </div>
                      )}

                      {/* Qty + discount + line total */}
                      {(() => {
                        const p = linePricing(item)
                        return (
                          <div className="flex flex-wrap items-center gap-2 mt-2.5">
                            <div className="flex items-center border border-gray-mid rounded-lg overflow-hidden">
                              <button onClick={() => updateQty(item.id, item.quantity - 1)} className="px-2.5 py-1 text-gray-dark hover:bg-gray text-sm font-bold">−</button>
                              <span className="px-3 py-1 text-sm font-bold font-bai text-foreground min-w-[30px] text-center">{item.quantity}</span>
                              <button onClick={() => updateQty(item.id, item.quantity + 1)} className="px-2.5 py-1 text-gray-dark hover:bg-gray text-sm font-bold">+</button>
                            </div>

                            <label className="flex items-center rounded-lg border border-gray-mid focus-within:border-primary focus-within:ring-2 focus-within:ring-primary/10" title="Discount %">
                              <span className="pl-2 text-[10px] font-semibold uppercase text-gray-dark font-pop">Disc</span>
                              <input
                                type="number"
                                inputMode="decimal"
                                min={0}
                                max={100}
                                step="0.5"
                                value={item.discount ? item.discount : ''}
                                onChange={e => updateDiscount(item.id, e.target.value === '' ? 0 : Number(e.target.value))}
                                placeholder="0"
                                aria-label={`Discount % for ${item.productName}`}
                                className="w-12 bg-transparent px-1.5 py-1 text-right text-sm font-bold font-bai text-foreground outline-none [appearance:textfield] [&::-webkit-inner-spin-button]:appearance-none [&::-webkit-outer-spin-button]:appearance-none"
                              />
                              <span className="pr-2 text-xs font-semibold text-gray-dark">%</span>
                            </label>

                            {p.total !== null && (
                              <div className="ml-auto text-right">
                                {p.disc > 0 && (
                                  <p className="text-[10px] text-gray-dark font-pop line-through">{formatInr(p.unit! * item.quantity)}</p>
                                )}
                                <p className="text-sm font-bold font-bai text-foreground">{formatInr(p.total)}</p>
                              </div>
                            )}
                          </div>
                        )
                      })()}
                    </div>
                  </div>
                </div>
              ))}
            </div>
          )}
        </div>

        {/* Footer */}
        {items.length > 0 && (
          <div className="border-t border-gray px-6 py-5 space-y-3 flex-shrink-0">
            <div className="space-y-1 text-sm">
              <div className="flex items-center justify-between">
                <span className="text-gray-text font-pop">Total items in quote</span>
                <span className="font-bold font-bai text-foreground">{totalQty}</span>
              </div>
              {quoteTotals.hasPrices && (
                <>
                  <div className="flex items-center justify-between">
                    <span className="text-gray-text font-pop">Subtotal (D.P.)</span>
                    <span className="font-semibold font-bai text-foreground">{formatInr(quoteTotals.gross)}</span>
                  </div>
                  {quoteTotals.discount > 0 && (
                    <div className="flex items-center justify-between">
                      <span className="text-gray-text font-pop">Discount</span>
                      <span className="font-semibold font-bai text-green-700">− {formatInr(quoteTotals.discount)}</span>
                    </div>
                  )}
                  <div className="flex items-center justify-between border-t border-gray pt-1.5">
                    <span className="font-semibold text-foreground font-pop">Total <span className="text-[11px] font-normal text-gray-dark">(excl. GST)</span></span>
                    <span className="text-base font-extrabold font-bai text-primary">{formatInr(quoteTotals.net)}</span>
                  </div>
                  {quoteTotals.unpriced > 0 && (
                    <p className="text-[11px] text-gray-dark font-pop">
                      {quoteTotals.unpriced} item{quoteTotals.unpriced === 1 ? '' : 's'} without a price — not included.
                    </p>
                  )}
                </>
              )}
            </div>
            <textarea
              value={note}
              onChange={e => setNote(e.target.value)}
              maxLength={2000}
              rows={2}
              placeholder="Add a note for LEDLUM (optional) — project name, delivery date…"
              className="w-full resize-none rounded-xl border border-gray-mid bg-white px-3 py-2 text-sm font-pop text-foreground placeholder:text-gray-dark outline-none focus:border-primary focus:ring-2 focus:ring-primary/10"
            />
            <button onClick={handleSendQuote} disabled={sending}
              className="w-full flex items-center justify-center gap-2 py-3 bg-primary hover:bg-primary-dark disabled:opacity-60 text-white rounded-xl font-bold font-bai text-sm transition-colors">
              {sending ? (
                <><div className="w-4 h-4 border-2 border-white border-t-transparent rounded-full animate-spin" /> Sending…</>
              ) : sent ? (
                <><svg width="15" height="15" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2.5"><polyline points="20 6 9 17 4 12"/></svg> Sent!</>
              ) : (
                <><svg width="15" height="15" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2"><line x1="22" y1="2" x2="11" y2="13"/><polygon points="22 2 15 22 11 13 2 9 22 2"/></svg> Send Quote Request</>
              )}
            </button>
            <div className="flex gap-2">
              <button onClick={handleCopyQuote}
                className="flex-1 flex items-center justify-center gap-1.5 py-2 border border-gray-mid rounded-lg text-sm font-semibold font-bai text-gray-text hover:border-foreground hover:text-foreground transition-colors">
                <svg width="13" height="13" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2"><rect x="9" y="9" width="13" height="13" rx="2"/><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"/></svg>
                Copy
              </button>
              {can('download') && (
                <button onClick={() => setBoqFormOpen(true)} disabled={downloadingPdf}
                  className="flex-1 flex items-center justify-center gap-1.5 py-2 border border-primary/30 rounded-lg text-sm font-semibold font-bai text-primary hover:bg-primary/5 disabled:opacity-60 transition-colors">
                  {downloadingPdf ? (
                    <div className="w-3.5 h-3.5 border-2 border-primary border-t-transparent rounded-full animate-spin" />
                  ) : (
                    <svg width="13" height="13" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2">
                      <path d="M21 15v4a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2v-4"/>
                      <polyline points="7 10 12 15 17 10"/>
                      <line x1="12" y1="15" x2="12" y2="3"/>
                    </svg>
                  )}
                  {downloadingPdf ? 'Generating…' : 'Download BOQ'}
                </button>
              )}
              <button onClick={() => { if (confirm('Clear all items from quote?')) clearCart() }}
                className="flex-1 flex items-center justify-center gap-1.5 py-2 border border-gray-mid rounded-lg text-sm font-semibold font-bai text-gray-text hover:border-red-400 hover:text-red-500 transition-colors">
                <svg width="13" height="13" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2"><polyline points="3 6 5 6 21 6"/><path d="M19 6v14a2 2 0 0 1-2 2H7a2 2 0 0 1-2-2V6m3 0V4a1 1 0 0 1 1-1h4a1 1 0 0 1 1 1v2"/></svg>
                Clear
              </button>
            </div>
          </div>
        )}
      </div>

      {/* ── BOQ project details form (opens from "Download BOQ") ── */}
      {boqFormOpen && (
        <div
          className="fixed inset-0 z-[70] flex items-center justify-center bg-black/40 p-5"
          onClick={() => setBoqFormOpen(false)}
          onKeyDown={e => { if (e.key === 'Escape') setBoqFormOpen(false) }}
        >
          <form
            onClick={e => e.stopPropagation()}
            onSubmit={e => { e.preventDefault(); handleDownloadPDF() }}
            className="w-full max-w-md overflow-hidden rounded-2xl bg-white shadow-2xl animate-fade-in"
          >
            <div className="h-1 bg-gradient-to-r from-primary to-primary-dark" />
            <div className="flex items-start justify-between border-b border-gray px-6 py-4">
              <div>
                <h3 className="text-lg font-bold font-bai text-foreground">BOQ details</h3>
                <p className="mt-0.5 text-xs text-gray-text font-pop">
                  Printed on the BOQ header. Leave any field empty to keep it blank.
                </p>
              </div>
              <button type="button" onClick={() => setBoqFormOpen(false)} aria-label="Close"
                className="w-8 h-8 rounded-full border border-gray flex items-center justify-center text-gray-dark hover:bg-primary hover:text-white hover:border-primary transition-all text-sm">
                ✕
              </button>
            </div>

            <div className="space-y-3 px-6 py-5">
              {([
                ['projectName',   'Project Name',   'e.g. R.K. Salai Experience Centre'],
                ['location',      'Location',       'e.g. Chennai'],
                ['architectName', 'Architect Name', 'e.g. Studio XYZ'],
              ] as [keyof BoqDetails, string, string][]).map(([key, label, ph], i) => (
                <div key={key}>
                  <label className="mb-1 block text-[11px] font-semibold uppercase tracking-wide text-gray-dark font-pop">{label}</label>
                  <input
                    type="text"
                    value={boqDetails[key]}
                    onChange={setBoqField(key)}
                    placeholder={ph}
                    autoFocus={i === 0}
                    className="w-full rounded-lg border border-gray-mid bg-white px-3 py-2.5 text-sm font-bai text-foreground outline-none placeholder:text-gray-dark focus:border-primary focus:ring-2 focus:ring-primary/10"
                  />
                </div>
              ))}
              <div>
                <label className="mb-1 block text-[11px] font-semibold uppercase tracking-wide text-gray-dark font-pop">Architect PAN</label>
                <input
                  type="text"
                  value={boqDetails.architectPan}
                  onChange={setBoqField('architectPan')}
                  placeholder="e.g. ABCDE1234F"
                  maxLength={10}
                  className={`w-full rounded-lg border bg-white px-3 py-2.5 text-sm font-bai uppercase text-foreground outline-none placeholder:normal-case placeholder:text-gray-dark focus:ring-2 ${
                    panInvalid ? 'border-red-400 focus:border-red-400 focus:ring-red-100' : 'border-gray-mid focus:border-primary focus:ring-primary/10'
                  }`}
                />
                {panInvalid && (
                  <p className="mt-1 text-[11px] text-red-500 font-pop">PAN should be 10 characters, like ABCDE1234F</p>
                )}
              </div>
            </div>

            <div className="flex items-center justify-between gap-3 border-t border-gray bg-gray px-6 py-4">
              <button type="button" onClick={() => setBoqDetails(EMPTY_BOQ_DETAILS)}
                className="text-xs font-semibold text-gray-dark hover:text-primary font-pop">
                Clear fields
              </button>
              <div className="flex gap-2">
                <button type="button" onClick={() => setBoqFormOpen(false)}
                  className="rounded-lg border border-gray-mid bg-white px-4 py-2.5 text-sm font-semibold font-bai text-gray-text hover:border-foreground">
                  Cancel
                </button>
                <button type="submit" disabled={panInvalid || downloadingPdf}
                  className="flex items-center gap-1.5 rounded-lg bg-primary px-5 py-2.5 text-sm font-bold font-bai text-white hover:bg-primary-dark disabled:opacity-50">
                  <svg width="13" height="13" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2">
                    <path d="M21 15v4a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2v-4"/><polyline points="7 10 12 15 17 10"/><line x1="12" y1="15" x2="12" y2="3"/>
                  </svg>
                  Download BOQ
                </button>
              </div>
            </div>
          </form>
        </div>
      )}
    </>
  )
}
