'use client'

import { useState } from 'react'
import Image from 'next/image'
import { useCart } from '@/context/CartContext'
import { useAuth } from '@/context/AuthContext'
import { useToast } from '@/context/ToastContext'
import { getZoneById } from '@/lib/zones'

export default function CartDrawer() {
  const { items, isOpen, closeCart, removeItem, updateQty, clearCart } = useCart()
  const { user } = useAuth()
  const { toast } = useToast()
  const [sending, setSending] = useState(false)
  const [sent, setSent] = useState(false)

  const totalQty = items.reduce((s, i) => s + i.quantity, 0)

  const buildEmailBody = () => {
    const header = `LEDLUM — Quote Request\n${'='.repeat(50)}\n\nVendor: ${user?.name ?? 'Unknown'}\nCompany: ${user?.company ?? '—'}\nEmail: ${user?.email ?? '—'}\nDate: ${new Date().toLocaleString('en-IN')}\n\n${'─'.repeat(50)}\nITEMS\n${'─'.repeat(50)}\n`

    const rows = items.map((item, i) => {
      const zone  = getZoneById(item.zone)?.label ?? item.zone
      const specs = Object.entries(item.selection)
        .filter(([, v]) => v)
        .map(([k, v]) => `  • ${k.charAt(0).toUpperCase() + k.slice(1)}: ${v}`)
        .join('\n')
      return `\n${i + 1}. ${item.productName}\n   Zone: ${zone}\n   Quantity: ${item.quantity}\n${specs || '   (No configuration selected)'}`
    }).join('\n')

    const footer = `\n\n${'─'.repeat(50)}\nTotal items: ${totalQty}\n\nPlease review and confirm pricing before processing.\n\nGenerated by LEDLUM Catalog System`

    return header + rows + footer
  }

  const handleSendQuote = async () => {
    if (items.length === 0) return
    setSending(true)

    const body    = buildEmailBody()
    const subject = `Quote Request — ${user?.company ?? user?.name ?? 'Vendor'} — ${new Date().toLocaleDateString('en-IN')}`
    const mailto  = `mailto:sales@ledlum.com?subject=${encodeURIComponent(subject)}&body=${encodeURIComponent(body)}`

    // Open mailto (falls back gracefully)
    window.location.href = mailto

    // Simulate sent state
    await new Promise(r => setTimeout(r, 800))
    setSent(true)
    setSending(false)
    toast('Quote request opened in your email client', 'success')
    setTimeout(() => setSent(false), 4000)
  }

  const handleCopyQuote = () => {
    navigator.clipboard.writeText(buildEmailBody())
    toast('Quote copied to clipboard', 'success')
  }

  return (
    <>
      {/* Backdrop */}
      <div
        className={`fixed inset-0 z-40 bg-black/40 transition-opacity duration-300 ${isOpen ? 'opacity-100 pointer-events-auto' : 'opacity-0 pointer-events-none'}`}
        onClick={closeCart}
      />

      {/* Drawer */}
      <div className={`fixed inset-y-0 right-0 z-50 w-full max-w-md bg-white shadow-2xl flex flex-col transition-transform duration-400 ease-[cubic-bezier(0.25,0.46,0.45,0.94)]
        ${isOpen ? 'translate-x-0' : 'translate-x-full'}
      `}>
        {/* Red top bar */}
        <div className="h-1 bg-gradient-to-r from-primary to-secondary flex-shrink-0" />

        {/* Header */}
        <div className="flex items-center justify-between px-6 py-4 border-b border-gray flex-shrink-0">
          <div>
            <h2 className="text-lg font-bold font-bai text-foreground flex items-center gap-2">
              <svg width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2"><circle cx="9" cy="21" r="1"/><circle cx="20" cy="21" r="1"/><path d="M1 1h4l2.68 13.39a2 2 0 0 0 2 1.61h9.72a2 2 0 0 0 2-1.61L23 6H6"/></svg>
              Quote Cart
            </h2>
            <p className="text-xs text-gray-text font-pop mt-0.5">
              {user?.company ?? user?.name} · {totalQty} item{totalQty !== 1 ? 's' : ''}
            </p>
          </div>
          <button onClick={closeCart}
            className="w-8 h-8 rounded-full border border-gray flex items-center justify-center text-gray-dark hover:bg-primary hover:text-white hover:border-primary transition-all text-sm">
            ✕
          </button>
        </div>

        {/* Items */}
        <div className="flex-1 overflow-y-auto">
          {items.length === 0 ? (
            <div className="flex flex-col items-center justify-center h-full text-center px-8">
              <svg className="opacity-10 mb-4" width="56" height="56" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1"><circle cx="9" cy="21" r="1"/><circle cx="20" cy="21" r="1"/><path d="M1 1h4l2.68 13.39a2 2 0 0 0 2 1.61h9.72a2 2 0 0 0 2-1.61L23 6H6"/></svg>
              <p className="text-gray-dark font-bai text-sm">Your quote cart is empty</p>
              <p className="text-gray-dark text-xs font-pop mt-1">Browse products and add configurations</p>
            </div>
          ) : (
            <div className="divide-y divide-gray">
              {items.map(item => (
                <div key={item.id} className="px-6 py-4">
                  <div className="flex gap-3">
                    {/* Thumb */}
                    <div className="w-14 h-14 bg-gray rounded-lg overflow-hidden flex-shrink-0 relative">
                      {item.productImage ? (
                        <img src={item.productImage} alt={item.productCode} className="w-full h-full object-cover" />
                      ) : (
                        <div className="w-full h-full flex items-center justify-center">
                          <svg className="opacity-20" width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.5"><rect x="3" y="3" width="18" height="18" rx="2"/><circle cx="8.5" cy="8.5" r="1.5"/><polyline points="21 15 16 10 5 21"/></svg>
                        </div>
                      )}
                    </div>

                    <div className="flex-1 min-w-0">
                      <div className="flex items-start justify-between gap-2">
                        <span className="font-bold text-sm font-bai text-foreground truncate">{item.productName}</span>
                        <button onClick={() => removeItem(item.id)}
                          className="text-gray-dark hover:text-primary transition-colors flex-shrink-0 mt-0.5">
                          <svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2"><polyline points="3 6 5 6 21 6"/><path d="M19 6v14a2 2 0 0 1-2 2H7a2 2 0 0 1-2-2V6m3 0V4a1 1 0 0 1 1-1h4a1 1 0 0 1 1 1v2"/></svg>
                        </button>
                      </div>
                      <p className="text-[10px] text-gray-dark font-pop">{getZoneById(item.zone)?.label ?? item.zone}</p>

                      {/* Selection chips */}
                      {Object.entries(item.selection).filter(([, v]) => v).length > 0 && (
                        <div className="flex flex-wrap gap-1 mt-1.5">
                          {Object.entries(item.selection).filter(([, v]) => v).map(([k, v]) => (
                            <span key={k} className="text-[9px] bg-gray border border-gray-mid rounded-full px-2 py-0.5 font-pop text-gray-text">
                              {v}
                            </span>
                          ))}
                        </div>
                      )}

                      {/* Qty controls */}
                      <div className="flex items-center gap-2 mt-2.5">
                        <div className="flex items-center border border-gray-mid rounded-lg overflow-hidden">
                          <button onClick={() => updateQty(item.id, item.quantity - 1)}
                            className="px-2.5 py-1 text-gray-dark hover:bg-gray text-sm font-bold">−</button>
                          <span className="px-3 py-1 text-sm font-bold font-bai text-foreground min-w-[30px] text-center">{item.quantity}</span>
                          <button onClick={() => updateQty(item.id, item.quantity + 1)}
                            className="px-2.5 py-1 text-gray-dark hover:bg-gray text-sm font-bold">+</button>
                        </div>
                      </div>
                    </div>
                  </div>
                </div>
              ))}
            </div>
          )}
        </div>

        {/* Footer actions */}
        {items.length > 0 && (
          <div className="border-t border-gray px-6 py-5 space-y-3 flex-shrink-0">
            <div className="flex items-center justify-between text-sm">
              <span className="text-gray-text font-pop">Total items in quote</span>
              <span className="font-bold font-bai text-foreground">{totalQty}</span>
            </div>

            <button onClick={handleSendQuote} disabled={sending}
              className="w-full flex items-center justify-center gap-2 py-3 bg-primary hover:bg-secondary disabled:opacity-60 text-white rounded-xl font-bold font-bai text-sm transition-colors">
              {sending ? (
                <span className="flex items-center gap-2">
                  <div className="w-4 h-4 border-2 border-white border-t-transparent rounded-full animate-spin" />
                  Opening email…
                </span>
              ) : sent ? (
                <span className="flex items-center gap-2">
                  <svg width="15" height="15" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2.5"><polyline points="20 6 9 17 4 12"/></svg>
                  Sent!
                </span>
              ) : (
                <span className="flex items-center gap-2">
                  <svg width="15" height="15" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2"><line x1="22" y1="2" x2="11" y2="13"/><polygon points="22 2 15 22 11 13 2 9 22 2"/></svg>
                  Send Quote Request
                </span>
              )}
            </button>

            <div className="flex gap-2">
              <button onClick={handleCopyQuote}
                className="flex-1 flex items-center justify-center gap-1.5 py-2 border border-gray-mid rounded-lg text-sm font-semibold font-bai text-gray-text hover:border-foreground hover:text-foreground transition-colors">
                <svg width="13" height="13" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2"><rect x="9" y="9" width="13" height="13" rx="2" ry="2"/><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"/></svg>
                Copy Quote
              </button>
              <button onClick={() => { if (confirm('Clear all items from quote?')) clearCart() }}
                className="flex-1 flex items-center justify-center gap-1.5 py-2 border border-primary/30 rounded-lg text-sm font-semibold font-bai text-primary hover:bg-primary/5 transition-colors">
                <svg width="13" height="13" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2"><polyline points="3 6 5 6 21 6"/><path d="M19 6v14a2 2 0 0 1-2 2H7a2 2 0 0 1-2-2V6m3 0V4a1 1 0 0 1 1-1h4a1 1 0 0 1 1 1v2"/></svg>
                Clear All
              </button>
            </div>
          </div>
        )}
      </div>
    </>
  )
}
